---
title: "Habbit"
author: "Awesome Me"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    number-sections: true
editor: visual
---

```{r setup, include = F}
library(tidyverse)
library(skimr)   # a better summary of data.frame
library(scales)  # scales for ggplot
library(ggthemes)  # additional ggplot themes
library(socviz)
theme_set(theme_minimal()) # setting the minimal theme for ggplot
# setting default chunk options
knitr::opts_chunk$set(echo = T, eval = T,
                      message=F, warning = F) 
```

## Quarterly Results {.tabset .tabset-pills}

### By Product

(tab content) 1

### By Region

(tab content) 2

```{r}
library(tidyverse)
ggplot(mpg) +
  geom_boxplot(aes(x = class, y = hwy))
```

# Example Title {.unnumbered}

Here is some example title.

## Section X

This is my introduction.

```{r}
x <- 1
print(x)
```

# Section 1

Wake up

## Section 1.1

Drink water

## Section 1.2

Sleep again

# Section 2

Wake up

# ggplot bar

```{r}
p <- ggplot(data = titanic,
            mapping = aes(x = fate, y = percent, fill = sex))
p + geom_bar(position = "dodge", stat = "identity") +
  theme(legend.position = "top")

```

`oecd_sum` bar to visualize the trend of `diff`

```{r}
oecd_sum

p <- ggplot(oecd_sum, aes(x = year, y = diff, fill = hi_lo ))

p + geom_col() +
  labs(x = NULL,
       caption = "first line\n second line")
```

```{r}
mpg <- mpg

p <- ggplot(mpg, aes(x = class, fill = drv))
p + geom_bar(position = "identity", alpha = .2)
```

-   `gapminder` practice

```{r, fig.height= 20, fig.width= 7}
library(gapminder)
gapminder <- gapminder
p <- ggplot(gapminder, aes( x = pop, y = gdpPercap )) 
p + geom_point(alpha = .3) +
  geom_smooth(method = lm) +
  facet_grid( year ~ .)
```

```{r, fig.height= 20, fig.width= 7}
p <- ggplot(gapminder, aes(x = lifeExp, y = gdpPercap)) 
p + geom_bin2d(bins = c(25, 100))
```

```{r}
gss_sm
?gss_sm
p <- ggplot(gss_sm, aes(x = bigregion, fill = religion))
p + geom_bar(position = "dodge2") 
```

```{r}
library(socviz)
gss_sm

rel_by_region <- gss_sm %>%
    group_by( bigregion, religion ) %>%
    summarize( N = n() ) %>%
    mutate( freq = N / sum(N),
            pct = round( (freq*100), 0) )
rel_by_region

```

```{r}
p <- ggplot( rel_by_region, 
             aes( x = bigregion, 
                  y = pct, 
                  fill = religion))
p + geom_col( position = "dodge2" ) +
    labs(x = "Region", 
         y = "Percent", 
         fill = "Religion") +
    theme(legend.position 
            = "top")

```

```{r}
library(hrbrthemes)
p <- ggplot(rel_by_region,
            aes(x = religion, y = pct, fill = religion ))
p + geom_col() + facet_grid( .~ bigregion) +
  coord_flip() + guides(fill = "none") + theme_ipsum() +
  labs(x = NULL, y = "Percent")
```

```{r}
organdata
skimr::skim(organdata)
p <- ggplot(organdata, aes(y = donors, x = year))
p + geom_point()
```

```{r}
organdata
# skimr::skim(organdata)
library(lubridate)
organdata <- organdata %>% 
  mutate(year = year(year))
organdata

p <- ggplot(organdata, aes(y = donors, x = factor(year)))
p + geom_boxplot()
```

```{r}
p <- ggplot(organdata, aes(x = year, y = donors))
p + geom_line() + facet_wrap(.~ country)
```
