---
title: "Homework 1 "
author: "Awesome Me"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc-location: left
    number-sections: true
editor: visual
---

------------------------------------------------------------------------

title: "Homework 1"

format: html

editor: visual

------------------------------------------------------------------------

```{r setup, include = F}
library(tidyverse)
library(skimr)   # a better summary of data.frame
library(scales)  # scales for ggplot
library(ggthemes)  # additional ggplot themes
theme_set(theme_minimal()) # setting the minimal theme for ggplot
# setting default chunk options
knitr::opts_chunk$set(echo = T, eval = T,
                      message=F, warning = F) 
```

# Q0

# ggplot

## Why ggplot is awesome

The following boxplot shows how the distribution of city MPG (`cty`) varies by a type of cars (`class`).

```{r mpg-box, eval=T, echo=T}
ggplot(mpg) +
  geom_boxplot(aes(x = class, y = cty, fill = class))
```


# Q1

# Q2
