---
title: "Team Project"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc-location: right
    number-sections: true
editor: visual
---


```{r setup, include = F}
library(tidyverse)
library(ggthemes)
knitr::opts_chunk$set(warning = F, message = F)

```

This is an example of the team project web-page.

<br>

## US county map of climate change belief in 2018

&nbsp;
__Estimated percentage who think that global warming is caused mostly by human activities__

```{r eval=TRUE, echo=TRUE, message=F, warning=F}
cc_belief_county <- read_csv(
  'https://bcdanl.github.io/data/cc_belief_county.csv'
)
```


```{r eval=TRUE, echo=TRUE, fig.asp=.75, message=FALSE, warning=FALSE}

legend_title <- ""

ggplot(data = cc_belief_county) +
  geom_polygon(aes(long, lat, group = group, 
                   fill = human2018),
               color = "grey", size = 0.1) +
  coord_map("bonne", parameters = 41.6) + 
  scale_fill_gradient(legend_title, 
                      low='#0057e7', 
                      high='#d62d20') +
  theme_map() + 
  theme(legend.position="right") +
  labs(caption = "Data source: Yale Climate Change Communication")
```


